services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api_container
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   ports:
  #     - "${PORT_SERVER}:3333"
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: npm run dev
 
  database:
    image: postgres:latest
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - data_sql:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  data_sql: